### ISSUE TITLE
Any chances to be on Unix-like systems?

### ISSUE THREAD

**Issue by lux01sv** [AntonMeep/vaniton#2]

**Comment by AntonMeep** [comment]
I am unsure what you mean, vaniton is cross-platform and I have checked it working on Debian.
Binaries provided on the [release](https://github.com/AntonMeep/vaniton/releases/tag/v1.3.0) page for linux-based systems are mostly static and should work on most of the systems. Otherwise it is always possible to compile vaniton yourself using gprbuild and any recent GNAT compiler
