### ISSUE TITLE
Can you add build instruction to readme?

### ISSUE THREAD

**Issue by zkhrg** [AntonMeep/vaniton#4]
I have some problems with build your project from source, ada and gpr is not popular tools so..
Add please build steps to readme

**Comment by AntonMeep** [comment]
Hello,

Setting up Ada compiler and gprbuild is system-dependent and can change drastically from one operating system version to another. Adding this information to the readme ensures that it would always be out of date :)

My advice would be to first check out your operating system's package manager, as for example Debian has both GNAT Ada compiler and gprbuild readily available. Otherwise, you could try [alire](https://alire.ada.dev/docs/#installation) that can pull the compiler and gprbuild along with all needed dependencies on other platforms such as Windows.

For build steps, check out GitHub workflow files for [Windows](https://github.com/AntonMeep/vaniton/blob/cd256a6cd931bd0bd2680a5f039032a160a7b052/.github/workflows/ci-windows.yml#L39) and [Linux](https://github.com/AntonMeep/vaniton/blob/cd256a6cd931bd0bd2680a5f039032a160a7b052/.github/workflows/ci-linux.yml#L29) - apart from installing the toolchain and some necessary libraries, the only command for building the application is

```
$ gprbuild -P vaniton.gpr -XBUILD=RELEASE -j0
```

Make sure to recursively clone the repository and have OpenSSL library installed.
